### ISSUE TITLE
준성씨께...

### ISSUE THREAD

**Issue by ijin1322** [SophieYoonseo/Jeonju_culturallife#15]
누구보다 제일 고생많은 @saechimdaeki 

게시판 DB 관련해서 클래스 추가 혹은 삭제된게 있나요? 있다면 댓글로 알려주세요! 

혹시 그리고.. 아이콘 확장자가 .png 인가요? 새로 안드로이드에 어플 설치해봤는데 아이콘 배경이 하얀색 네모여서 별로 안예쁘네요. 확인부탁드립니다. 그리고 제일 중요한게. 아이콘을 그렇게 배경에 상관없는 png확장자로 수정했다면 저에게 카톡으로 보내주십시요. 이 글 보는 즉시요! 다른용도로 쓸게 있어서 그렇습니다!

**Comment by saechimdaeki** [comment]
게시판 클래스 관련해서 추가 삭제된거없습니다

**Comment by ijin1322** [comment]
@saechimdaeki 새침하시긴ㅎㅎ :-) 👍 고맙습니다.

**Comment by saechimdaeki** [comment]
함수 + 기능만 추가함 방금

**Comment by saechimdaeki** [comment]
디자인 윤서담당이라 윤서한테 물어봐야합니당 단톡 ㄱㄱ
